Added ability to review PRs
AFPy/PyDocTeur pull request #59
Opened 2020-12-28 17:34 UTC by Seluj78

Closes #27

2020-12-28 21:49 UTC, awecx requested changes
Très bonne initiative de punir sur les msgid modifiés et les espaces manquantes.

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +        body = CHANGE_BODY.format(new_line=line, version=VERSION)
À quoi sert le _version_ ici ? Copié-collé de` REVIEW_BODY.format()` ?

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +Il t'es parfaitement possible de les ignorer car je peux faire des erreurs ! Merci de ta contribution.
```suggestion
Hello @$AUTHOR, j'ai trouvé automatiquement quelques changements à faire dans ta PR.
Il t'est parfaitement possible de les ignorer car je peux faire des erreurs ! Merci de ta contribution.
```

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +                        "fait une pull request dans CPython.\n\n" + body,
```suggestion
                        "fais une pull request dans CPython.\n\n" + body,
```

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +    return comments
Encore une fois, je ne suis pas entièrement convaincu de l'intérêt de signaler les espaces insécables _en trop_.
C'est fréquent d'en oublier … mais beaucoup moins d'en ajouter par erreur.
En plus il y a certains ensembles comme _p.  ex._ ou _van Rossum_ qui demandent une espacé insécable.

Je suggère de supprimer cette vérif' ou de changer le message pour rappeler, encore une fois, que PyDocteur peut faire des erreurs.

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +    last_commit = [commit for commit in pr.get_commits()][-1]
Ou pour être swag
```suggestion
    *_, last_commit = pr.get_commits()
```
?

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +            if line.startswith("msgid"):
J'aurais mis ça dans une fonction pour être au même niveau que `find_[missing|extraneous]_nb_spaces`

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +            if index in positions_to_ignore:
C'est vraiment utile ? PyDocteur est toujours le premier à commenter à moins que le relecteur soit _très_ rapide non ?

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +        line = line[:error_start] + "\xa0" + line[error_start + 1 :]  # noqa
Avec un test alors.

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +        body = CHANGE_BODY.format(new_line=line, version=VERSION)
Pareil, pas de _version_.

2020-12-28 21:49 UTC, awecx commented on pydocteur/review_pr.py
> +  <summary>Disclaimer</summary>
```suggestion
  <summary>Avertissement</summary>
```

2020-12-28 21:52 UTC, Seluj78 commented on pydocteur/review_pr.py
> +        body = CHANGE_BODY.format(new_line=line, version=VERSION)
Oui 😭

2020-12-28 21:52 UTC, Seluj78 commented on pydocteur/review_pr.py
> +        body = CHANGE_BODY.format(new_line=line, version=VERSION)
Artéfact de l'ancienne version

2020-12-28 21:54 UTC, Seluj78 commented on pydocteur/review_pr.py
> +    last_commit = [commit for commit in pr.get_commits()][-1]
Oh je connaissait pas, ca fait pareil ?

2020-12-28 21:56 UTC, Seluj78 commented on pydocteur/review_pr.py
> +            if index in positions_to_ignore:
Bha justement ça dépends de comment est implémenté review_pr (genre quand est ce que cette fnctiin est appelée), et les `positions_to_ignore` c'est pour que il se répéte pas deux fois...

2020-12-28 21:56 UTC, Seluj78 commented on pydocteur/review_pr.py
> +        line = line[:error_start] + "\xa0" + line[error_start + 1 :]  # noqa
Uh ?

2020-12-28 22:17 UTC, awecx commented on pydocteur/review_pr.py
> +    last_commit = [commit for commit in pr.get_commits()][-1]
Si `pr.get_commits()` est bien un générateur, oui.

2020-12-28 22:19 UTC, awecx commented on pydocteur/review_pr.py
> +        line = line[:error_start] + "\xa0" + line[error_start + 1 :]  # noqa
Je disais, si la ligne est mystique, elle mérite au moins d'être protégé par un unit test.
Je relis à tête reposée demain, il est trop tard pour faire de la regexp là.

2020-12-31 09:48 UTC, JulienPalard commented
Je pense que pour les espaces insécables on pourrait mieux profiter d'un outil qu'on peut faire fonctionner aussi en local et qu'on pourrait rajouter dans le workflow de test plutôt que dans le bot.

Le fait de ne pas coder cet outil dans le bot colle aussi a la philosophie "Do one thing and do it well" : le bot ne devrait faire qu'une seule chose, et le faire bien, alors que cette PR lui greffe d'autres choses à faire. (La chose pour laquel on l'a crée : commit un coup de powrap juste avant le merge).

2020-12-31 10:03 UTC, Seluj78 commented
Ouais je comprends la philosophie, j'ai juste un peu le seum d'avoir passé une demi journée dessus du coup 🤷

2021-01-22 16:28 UTC, JulienPalard commented
> Ouais je comprends la philosophie, j'ai juste un peu le seum d'avoir passé une demi journée dessus du coup shrug

Je comprend et je compatis. Ça s'appelle le biais du [coût irrécupérable](https://fr.wikipedia.org/wiki/Co%C3%BBt_irr%C3%A9cup%C3%A9rable).

Une chaîne que j'aime  bien à fait une vidéo sur le sujet : https://invidious.fdn.fr/watch?v=GCmfXMMhRzk

2021-01-22 17:27 UTC, Seluj78 commented
Ah stylé ! Je vais regarder la video !

2021-01-22 17:27 UTC, closed without merging