I don't think 'Issue comments' is a used action.
AFPy/PyDocTeur pull request #73
Opened 2021-06-04 15:51 UTC by JulienPalard

But it cause 503s when we:
```
issue_number = payload.get("issue", {}).get("number")
if issue_number:
    return gh_repo.get_pull(issue_number)
```

in case it's really an issue and not a PR, it raises an exception here.

2021-06-04 19:26 UTC, Seluj78 approved these changes

2021-06-04 19:27 UTC, Seluj78 commented
Oh no wait

2021-06-04 19:28 UTC, Seluj78 commented
Issue comments is a used action ! Pull requests and issue comments are the same

https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment

2021-06-04 19:28 UTC, Seluj78 requested changes
They are needed

2021-06-05 08:08 UTC, JulienPalard commented
so I tried to fix it the other way around :D

2021-06-05 09:30 UTC, Seluj78 approved these changes

2021-06-05 09:44 UTC, merged